/********************************************************************
* tmp/EventHeaderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/EventHeaderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEventHeaderDict();
extern void G__cpp_setup_inheritanceEventHeaderDict();
extern void G__cpp_setup_typetableEventHeaderDict();
extern void G__cpp_setup_memvarEventHeaderDict();
extern void G__cpp_setup_globalEventHeaderDict();
extern void G__cpp_setup_memfuncEventHeaderDict();
extern void G__cpp_setup_funcEventHeaderDict();
extern void G__set_cpp_environmentEventHeaderDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/EventHeader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EventHeaderDictLN_TClass;
extern G__linked_taginfo G__EventHeaderDictLN_TBuffer;
extern G__linked_taginfo G__EventHeaderDictLN_TMemberInspector;
extern G__linked_taginfo G__EventHeaderDictLN_TObject;
extern G__linked_taginfo G__EventHeaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EventHeaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventHeaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EventHeaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventHeaderDictLN_EventHeader;

/* STUB derived class for protected member access */
